export enum Distance {
  Meter = 'Meter',
  Kilometer = 'Kilometer',
  Centimeter = 'Centimeter',
  Millimeter = 'Millimeter',
  Micrometer = 'Micrometer',
  Nanometer = 'Nanometer',
  Mile = 'Mile',
  Yard = 'Yard',
  Foot = 'Foot',
  Inch = 'Inch',
}

export enum Area {
  SquareMeter = 'Square Meter',
  SquareKilometer = 'Square Kilometer',
  SquareCentimeter = 'Square Centimeter',
  SquareMillimeter = 'Square Millimeter',
  SquareMicrometer = 'Square Micrometer',
  Hectare = 'Hectare',
  SquareMile = 'Square Mile',
  SquareYard = 'Square Yard',
  SquareFoot = 'Square Foot',
  SquareInch = 'Square Inch',
  Acre = 'Acre',
}

export enum Volume {
  CubicMeter = 'Cubic Meter',
  CubicKilometer = 'Cubic Kilometer',
  CubicCentimeter = 'Cubic Centimeter',
  CubicMillimeter = 'Cubic Millimeter',
  Liter = 'Liter',
  Milliliter = 'Milliliter',
  USGallon = 'US Gallon',
  USQuart = 'US Quart',
  USPint = 'US Pint',
  USCup = 'US Cup',
  USFluidOunce = 'US Fluid Ounce',
  USTableSpoon = 'US Table Spoon',
  USTeaSpoon = 'US Tea Spoon',
  ImperialGallon = 'Imperial Gallon',
  ImperialQuart = 'Imperial Quart',
  ImperialPint = 'Imperial Pint',
  ImperialFluidOunce = 'Imperial Fluid Ounce',
  ImperialTableSpoon = 'Imperial Table Spoon',
  ImperialTeaSpoon = 'Imperial Tea Spoon',
  CubicMile = 'Cubic Mile',
  CubicYard = 'Cubic Yard',
  CubicFoot = 'Cubic Foot',
  CubicInch = 'Cubic Inch',
}

export enum Speed {
  CMPH = 'Centimeter/Hour',
  CMPMIN = 'Centimeter/Minute',
  CMPS = 'Centimeter/Second',
  FTPH = 'Foot/Hour',
  FTPMIN = 'Foot/Minute',
  FTPS = 'Foot/Second',
  KMPH = 'Kilometer/Hour',
  KMPMIN = 'Kilometer/Minute',
  KMPS = 'Kilometer/Second',
  MIPH = 'Mile/Hour',
  MIPMIN = 'Mile/Minute',
  MIPS = 'Mile/Second',
  MMPH = 'Millimeter/Hour',
  MMPMIN = 'Millimeter/Minute',
  MMPS = 'Millimeter/Second',
  MPH = 'Meter/Hour',
  MPMIN = 'Meter/Minute',
  MPS = 'Meter/Second',
  YDPH = 'Yard/Hour',
  YDPMIN = 'Yard/Minute',
  YDPS = 'Yard/Second',
}
